# Generated by Django 5.0.4 on 2024-05-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_userprofile_is_active_userprofile_is_admin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
