# Generated by Django 5.0.4 on 2024-05-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
