# Generated by Django 5.0.4 on 2024-05-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='booking',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
